module.exports = [
{
    title: "Good Fellas",
    genre: "Biography/Crime/Drama",
    image: "https://i.ebayimg.com/images/g/0w8AAOSwkoxiQ0hl/s-l500.jpg",
    director: "Martin Scorsese",
    stream: "Netflix: Subscription",
    streamTwo: "HBO Max: Subscription",
    streamThree: "Vudu: $3.99",
    year: "1990",
    description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate."
},   
{
    title: "The Big Short",
    genre: "Biography/Comedy/Drama",
    image: "https://flxt.tmsimg.com/assets/p12157971_p_v8_ae.jpg",
    director: "Adam McKay",
    stream: "Vudu: $2.99",
    streamTwo: "Amazon Prime Video: $2.99",
    streamThree: "Apple TV: $3.99",
    year: "2015",
    description: "In 2006-2007 a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is."
}, 
{
    title: "Taxi Driver",
    genre: "Drama",
    image: "https://res.cloudinary.com/jerrick/image/upload/v1622658281/60b7cce92eefc1001d04b3ab.jpg",
    director: "Martin Scorsese",
    stream: "Netflix: Subscription",
    streamTwo: "Vudu: $2.99",
    streamThree: "Apple TV: $3.99",
    year: "1976",
    description: "Suffering from insomnia, disturbed loner Travis Bickle (Robert De Niro) takes a job as a New York City cabbie, haunting the streets nightly, growing increasingly detached from reality as he dreams of cleaning up the filthy city. When Travis meets pretty campaign worker Betsy (Cybill Shepherd), he becomes obsessed with the idea of saving the world, first plotting to assassinate a presidential candidate, then directing his attentions toward rescuing 12-year-old prostitute Iris (Jodie Foster)"
},
{
    title: "Gangs of New York",
    genre: "Drama/Crime",
    image: "https://1.bp.blogspot.com/-CpbaFkjKlso/WnlKgDoLPMI/AAAAAAAAAKY/BBsqhV2Ukwoi_HznILdqmJTvbuUAvYdXQCLcBGAs/s1600/gangs_of_new_york_ver1_xlg.jpg",
    director: "Martin Scorsese",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Starz: Subscription",
    streamThree: "Vudu: $2.99",
    year: "2002",
    description: "In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father's killer."
},
{
    title: "Silence",
    genre: "Drama/History",
    image: "https://cps-static.rovicorp.com/2/Open/Paramount_Pictures_1103/Program/22107795/_derived_jpg_q90_310x470_m0/Silence_Parallax_2000x3000.jpg",
    director: "Martin Scorsese",
    stream: "Paramount+: Subscription",
    streamTwo: "Vudu: $2.99",
    streamThree: "Apple TV: $3.99",
    year: "2016",
    description: "In the 17th century, two Portuguese Jesuit priests travel to Japan in an attempt to locate their mentor, who is rumored to have committed apostasy, and to propagate Catholicism."
},
{
    title: "Inherent Vice",
    genre: "Comedy/Crime/Drama",
    image: "https://flxt.tmsimg.com/assets/p10598078_p_v8_bb.jpg",
    director: "Paul Thomas Anderson",
    stream: "Vudu: $2.99",
    streamTwo: "Apple TV: $2.99",
    streamThree: "Amazon Prime Video: $2.99",
    year: "2014",
    description: "In 1970, drug-fueled Los Angeles private investigator Larry Doc Sportello investigates the disappearance of a former girlfriend."
},
{
    title: "The Master",
    genre: "Drama",
    image: "https://upload.wikimedia.org/wikipedia/en/0/08/TheMaster2012Poster.jpg",
    director: "Paul Thomas Anderson",
    stream: "YouTube: $2.99",
    streamTwo: "Vudu: $3.99",
    streamThree: "Apple TV: $3.99",
    year: "2012",
    description: "A Naval veteran arrives home from war unsettled and uncertain of his future - until he is tantalized by the Cause and its charismatic leader."
},
{
    title: "Phantom Thread",
    genre: "Romance/Drama",
    image: "https://m.media-amazon.com/images/M/MV5BMWJkNzBkM2UtYWFlMC00NmEwLTgxOGUtMjVmMzYyZjgyMmEzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg",
    director: "Paul Thomas Anderson",
    stream: "Netflix: Subscription",
    streamTwo: "Vudu: $3.99",
    streamThree: "Apple TV: $3.99",
    year: "2017",
    description: "A fashion designer is drawn to a waitress, who becomes his model, muse and lover. With time, their relationship grows in intensity — and strangeness."
},
{
    title: "The Grand Budapest Hotel",
    genre: "Comedy/Drama",
    image: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_.jpg",
    director: "Wes Anderson",
    stream: "HBO Max: Subscription",
    streamTwo: "Hulu: Premium Subscription",
    streamThree: "Apple TV: $3.99",
    year: "2014",
    description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge."
},
{
    title: "The Darjeeling Limited",
    genre: "Adventure/Comedy/Drama",
    image: "http://thecinemaarchives.com/wp-content/uploads/2018/04/darjeeling-limited-poster.jpg",
    director: "Wes Anderson",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Starz: Subscription",
    streamThree: "Apple TV: $3.99",
    year: "2007",
    description: "A year after their father's funeral, three brothers travel across India by train in an attempt to bond with each other."
},
{
    title: "Rushmore",
    genre: "Comedy/Drama/Romance",
    image: "https://m.media-amazon.com/images/I/716wYQ6cGGS._SY445_.jpg",
    director: "Wes Anderson",
    stream: "Apple TV: $3.99",
    streamTwo: "Vudu: $3.99",
    streamThree: "Amazon Prime Video: $3.99",
    year: "1998",
    description: "Max Fischer (Jason Schwartzman) is a 10th-grader on scholarship at the tony private school Rushmore Academy. Max shows his devotion to the academy by participating in every possible extracurricular activity, but he's risking expulsion unless his grades improve. Max falls for one of the teachers, a beautiful young widow (Olivia Williams). And he connects with Blume (Bill Murray), a rich academy alumnus who is drawn to Max's passions and even acts as a go-between for Max's absurd attempt at courtship, until he himself becomes attracted to the teacher."
},
{
    title: "Birdman",
    genre: "Drama/Comedy",
    image: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/birdman-2014/large_yt5dLcIBQYodlComqy76Z3vwJ6e.jpg",
    director: "Alejandro Inarritu",
    stream: "Apple TV: $3.99",
    streamTwo: "Vudu: $3.99",
    streamThree: "Amazon Prime Video: $3.99",
    year: "2014",
    description: "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production."
},
{
    title: "The King's Speech",
    genre: "Biography/History/Drama",
    image: "https://flxt.tmsimg.com/assets/p8073374_p_v13_bb.jpg",
    director: "Tom Hooper",
    stream: "Starz: Subscription",
    streamTwo: "Hulu: Premium Subscription",
    streamThree: "Apple TV: $3.99",
    year: "2010",
    description: "The story of King George VI, his impromptu ascension to the throne of the British Empire in 1936, and the speech therapist who helped the unsure monarch overcome his stammer."
},
{
    title: "Slumdog Millionaire",
    genre: "Crime/Drama/Romance",
    image: "https://img.yts.mx/assets/images/movies/Slumdog_Millionaire_2008/medium-cover.jpg",
    director: "Danny Boyle & Loveleen Tandan",
    stream: "Hulu: Subscription",
    streamTwo: "Apple TV: $3.99",
    streamThree: "Vudu: $3.99",
    year: "2008",
    description: "A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of 'Who Wants to be a Millionaire?'"
},
{
    title: "Million Dollar Baby",
    genre: "Drama/Sport",
    image: "https://irs.www.warnerbros.com/keyart-jpeg/million_dollar_baby_keyart.jpg",
    director: "Clint Eastwood",
    stream: "HBO Max: Subscription",
    streamTwo: "Vudu: $3.99",
    streamThree: "Apple TV: $3.99",
    year: "2004",
    description: "A determined woman works with a hardened boxing trainer to become a professional."
},
{
    title: "Crash",
    genre: "Crime/Drama/Thriller",
    image: "https://upload.wikimedia.org/wikipedia/en/d/d0/Crash_ver2.jpg",
    director: "Paul Haggis",
    stream: "Apple TV: $3.99",
    streamTwo: "Vudu: $3.99",
    streamThree: "Amazon Prime Video: $3.99",
    year: "2004",
    description: "Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption."
},
{
    title: "American Hustle",
    genre: "Crime/Drama",
    image: "https://m.media-amazon.com/images/I/81BLAFWmSjL._SL1500_.jpg",
    director: "David O. Russell",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Starz: Subscription",
    streamThree: "Vudu: $2.99",
    year: "2013",
    description: "A con man, Irving Rosenfeld, along with his seductive partner Sydney Prosser, is forced to work for a wild F.B.I. Agent, Richie DiMaso, who pushes them into a world of Jersey powerbrokers and the Mafia."
},
{
    title: "Inglorious Basterds",
    genre: "Adventure/Drama/War",
    image: "https://m.media-amazon.com/images/I/71t14nj8cKL._SY606_.jpg",
    director: "Quentin Tarantino",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Apple TV: $3.99",
    streamThree: "Vudu: $3.99",
    year: "2009",
    description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same."
},
{
    title: "Fight Club",
    genre: "Drama",
    image: "https://images.squarespace-cdn.com/content/v1/55535a52e4b0e5d3276b0c3b/1607978252849-OUJA0DW8KE99Y3OXQKAF/676414_poster_l.jpg",
    director: "David Fincher",
    stream: "Apple TV: $3.99",
    streamTwo: "Vudu: $3.99",
    streamThree: "Amazon Prime Video: $3.99",
    year: "1999",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more."
},
{
    title: "Seven",
    genre: "Crime/Drama/Mystery",
    image: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/seven-1995/large_mhFXxB76LVgJBIfJM1sAuVBtVKv.jpg",
    director: "David Fincher",
    stream: "Netlfix: Subscription",
    streamTwo: "Apple TV: $3.99",
    streamThree: "Vudu: $3.99",
    year: "1995",
    description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives."
},
{
    title: "It Comes at Night",
    genre: "Horror/Mystery/Drama",
    image: "https://images.mymovies.net/images/film/cin/350x522/fid17723.jpg",
    director: "Trey Shults",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Amazon: Premium Subscription",
    streamThree: "Vudu: $2.99",
    year: "2017",
    description: "Secure within a desolate home as an unnatural threat terrorizes the world, a man has established a tenuous domestic order with his wife and son. Then a desperate young family arrives seeking refuge."
},
{
    title: "Interstellar",
    genre: "Sci-Fi/Adventure/Drama",
    image: "https://i.pinimg.com/originals/11/1c/5c/111c5c9ad99661af2d80e38948cf29d8.jpg",
    director: "Christopher Nolan",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Paramount+: Subscription",
    streamThree: "Vudu: $2.99",
    year: "2014",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."
},
{
    title: "Once Upon a Time in Hollywood",
    genre: "Comedy/Drama",
    image: "https://alternativemovieposters.com/wp-content/uploads/2020/02/monica_hollywood.jpg",
    director: "Quentin Tarantino",
    stream: "Hulu: Premium Subscription",
    streamTwo: "Vudu: $2.99",
    streamThree: "Apple TV: $3.99",
    year: "2019",
    description: "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles."
},
{
    title: "No Country for Old Men",
    genre: "Crime/Drama/Thriller",
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348662669l/6420913.jpg",
    director: " Ethan & Joel Coen",
    stream: "HBO Max: Subscription",
    streamTwo: "Hulu: Premium Subscription",
    streamThree: "Vudu: $2.99",
    year: "2007",
    description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande."
},
{
    title: "The Dark Knight",
    genre: "Crime/Drama/Action",
    image: "https://cdn.europosters.eu/image/750/plastic-frame-the-dark-knight-joker-gun-i23667.jpg",
    director: "Christopher Nolan",
    stream: "HBO Max: Subscription",
    streamTwo: "Apple TV: $3.99",
    streamThree: "Vudu: $3.99",
    year: "2008",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
},
{
    title: "Vice",
    genre: "Biography/Comedy",
    image: "https://m.media-amazon.com/images/M/MV5BMTY1NjM0MzgxMV5BMl5BanBnXkFtZTgwNDc4NTY0NjM@._V1_.jpg",
    director: "Adam McKay",
    stream: "Netflix: Subscription",
    streamTwo: "Apple TV: $3.99",
    streamThree: "Vudu: $3.99",
    year: "2018",
    description: "The story of Dick Cheney, an unassuming bureaucratic Washington insider, who quietly wielded immense power as Vice President to George W. Bush, reshaping the country and the globe in ways that are still felt today."
}

]